name: Node w/ TS CI Pipeline

on:
  push:

jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2

    - name: Init
      uses: actions/setup-node@v2
      with:
        node-version: 15

    - name: Install
      run: rm -rf node_modules && yarn install --frozen-lockfile

    - name: Build
      run: yarn build

    - name: Lint
      run: yarn lint
      
    - name: Test
      run: yarn test